import subprocess

#proc = subprocess.Popen('apt-get install -y libc6:i386', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()
#print('done')
#proc = subprocess.Popen('apt-get install -y libbz2-1.0:i386', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()
#print('done')
#proc = subprocess.Popen('apt-get install -y patch make cmake g++ pkg-config libx11-dev libxext-dev libxtst-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libasound2-dev lib32z1', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()
#print('done')
#proc = subprocess.Popen('dpkg --add-architecture i386', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()
#print('done')
#proc = subprocess.Popen('apt-get update', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()
#print('done')
#proc = subprocess.Popen('apt-get install -y ia32-libs', shell=True, stdin=None, stdout=open("/dev/null", "w"), stderr=None, executable="/bin/bash")
#proc.wait()